// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ObligatoriskOpgave2.Models
{
    [Table("Facilitet")]
    public partial class Facilitet
    {
        public Facilitet()
        {
            Hotels = new HashSet<Hotel>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(70)]
        public string Title { get; set; }

        [ForeignKey("FacilitetId")]
        [InverseProperty("Facilitets")]
        public virtual ICollection<Hotel> Hotels { get; set; }

        public override string ToString()
        {
            return $"Facilitet ID er {Id}, og faciliteten hedder {Title}";
        }
    }
}