// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ObligatoriskOpgave2.Models
{
    [Table("Hotel")]
    public partial class Hotel
    {
        public Hotel()
        {
            Facilitets = new HashSet<Facilitet>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(70)]
        [Unicode(false)]
        public string Name { get; set; }
        [Required]
        [StringLength(100)]
        [Unicode(false)]
        public string Addresse { get; set; }

        [ForeignKey("HotelId")]
        [InverseProperty("Hotels")]
        public virtual ICollection<Facilitet> Facilitets { get; set; }

        public override string ToString()
        {
            return $"Id'et på hotellet er {Id}, navnet på hotellet er {Name}, adressen er {Addresse}";
        }
    }
}